### ISSUE TITLE
[BUG] '스탬프 찍기'기능 Webcam Error

### ISSUE THREAD

**Issue by YOOGOMJA** [likelion-syu/syu-fest#13]
**버그 설명**
스탬프 찍기 페이지 접근시 WebcamError 발생

**의도한 행동**
스탬프 찍기 페이지 조회

**Smartphone (환경을 제시해주세요):**
 - Device: 갤럭시 9
 - Browser : 카톡 인 브라우저

**Comment by syujisu** [comment]
체육대회 푸드트럭 부스 클릭 후 팝업창 스크롤 안됨(뒤에 배경이 스크롤)

**Comment by syujisu** [comment]
체육대회 이벤트 페이지 로고 부분 여백 발생 

- Device : 아이폰7
- Brower : 사파리

**Comment by syujisu** [comment]
축제 페이지 나브바 부스방문페이지 클릭 시 에러페이지 

- Device : 아이폰7
- Brower : 사파리
