### ISSUE TITLE
축제페이지 치어대전 동영상 재생 종료 시 다른 동영상으로 넘어감

### ISSUE THREAD

**Issue by syujisu** [likelion-syu/syu-fest#23]
**버그 설명**
축제페이지 치어대전 동영상 재생 종료 시 다른 동영상으로 넘어감

**의도한 행동**
치어대전 동영상 재생 시  관련없는 영상으로 넘어감

**Smartphone (환경을 제시해주세요):**
 - Device: 갤 8
- Browser :  카톡 인 크롬

**Comment by YOOGOMJA** [comment]
그건 동영상 변경되면 바뀔 예정입니다
