### ISSUE TITLE
팝업 작동시 백그라운드 스크롤만 작동

### ISSUE THREAD

**Issue by baeseonghyeon** [likelion-syu/syu-fest#7]
아이폰x 

팝업 작동시 팝업스크롤이 안먹히고 백그라운드 스크롤이 작동합니다.

**Comment by YOOGOMJA** [comment]
체육대회 페이지 한정인듯. 축제 페이지들은 팝업 스크롤이 잘됨

**Comment by baeseonghyeon** [comment]
dev b4f6e7d  에 해당사항 픽스
